#!/usr/bin/env python
# coding: utf-8

# # The Production Function

# To produce goods or services for sale, a firm must transform inputs into output. The quantity of output a firm produces depends on the quantity of inputs. This relationship is known as the firm's **production function**.
# 
# Production function
# : Relationship between the quantity of inputs a firms uses and the quantity of output it produces.

# ```{admonition} Definitions
# Before we start, there are some definitions to declare.
# 
# Total product/TP
# : Total output or quantity produced.<br><br>
# 
# Marginal product/MP
# : Additional output generated by an additional input (worker).
# : <math xmlns="http://www.w3.org/1998/Math/MathML">
#   <mi>M</mi>
#   <mi>P</mi>
#   <mo>=</mo>
#   <mfrac>
#     <mrow>
#       <mi mathvariant="normal">&#x0394;<!-- Δ --></mi>
#       <mtext>Total Product</mtext>
#     </mrow>
#     <mrow>
#       <mi mathvariant="normal">&#x0394;<!-- Δ --></mi>
#       <mi>I</mi>
#       <mi>n</mi>
#       <mi>p</mi>
#       <mi>u</mi>
#       <mi>t</mi>
#       <mi>s</mi>
#     </mrow>
#   </mfrac>
# </math>
# 
# Average product/AP
# : Output per unit of input.
# : <math xmlns="http://www.w3.org/1998/Math/MathML">
#   <mi>A</mi>
#   <mi>P</mi>
#   <mo>=</mo>
#   <mfrac>
#     <mtext>Total Product</mtext>
#     <mtext>Units of Inputs</mtext>
#   </mfrac>
# </math>
# <br>
# 
# Marginal cost/MC
# : Additional cost incurred by an additional output.
# : <math xmlns="http://www.w3.org/1998/Math/MathML">
#   <mi>M</mi>
#   <mi>C</mi>
#   <mo>=</mo>
#   <mfrac>
#     <mrow>
#       <mi mathvariant="normal">&#x0394;<!-- Δ --></mi>
#       <mi>C</mi>
#       <mi>o</mi>
#       <mi>s</mi>
#       <mi>t</mi>
#     </mrow>
#     <mrow>
#       <mi mathvariant="normal">&#x0394;<!-- Δ --></mi>
#       <mi>O</mi>
#       <mi>u</mi>
#       <mi>t</mi>
#       <mi>p</mi>
#       <mi>u</mi>
#       <mi>t</mi>
#     </mrow>
#   </mfrac>
# </math>
# 
# Fixed cost/FC:
# : Cost that does not depend on the quantity of output produced. It is the cost of
# the fixed input.
# : e.g. rent, machines.<br><br>
# 
# Variable cost/VC
# : Cost that depends on the quantity of output produced.
# : e.g. Cost of labor, which is equal to the number of workers multiplied by weekly pay.<br><br>
# 
# Total cost/TC
# : TC = FC + VC<br><br>
# 
# Average variable cost/AVC
# : <math xmlns="http://www.w3.org/1998/Math/MathML">
#   <mi>A</mi>
#   <mi>V</mi>
#   <mi>C</mi>
#   <mo>=</mo>
#   <mfrac>
#     <mrow>
#       <mi>V</mi>
#       <mi>C</mi>
#     </mrow>
#     <mtext>Units of Outputs</mtext>
#   </mfrac>
# </math>
# ```

# (content:references:label_diminishingmp)=
# ### Law of Diminishing Marginal Returns
# 
# ```{Important}
# The **law of diminishing marginal returns** states that:<br><br>
# As variable resources (workers) are added to fixed resources (ovens, machinery, tool, etc.), the additional output produced from each additional  worker will **eventually** fall.
# ```

# ### Example of the Production Function
# 
# **Data**<br>
# <img src="../pic/unit03_1_table.png" alt="table" width="500"/>
# <br><br>
# **Production function**
# - Stage one: increasing marginal returns
# - Stage two: diminishing marginal returns, but still positive
# - Stage three: negative marginal returns
# <br>
# <img src="../pic/unit03_1_tp.png" alt="tp" width="600"/>

# > As shown in the figure below:
# > - MP and MC curves are mirror images of each other.
# > - AP and AVC curves are also mirror images.
# > - TP is at its highest point where MP turns negative.

# <img src="../pic/unit03_1_avc.png" alt="avc" width="600"/>

# ```{admonition} Summary
# **Production function** consists of
# - x-axis: # of inputs
# - y-axis: outputs
# - Total product curve
# - Marginal product curve
# - Average product curve
# - 3 stages
#     1. MP is rising;
#     2. MP is falling;
#     3. MP is negative.
# ```
